apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: testapp-prod
  ports:
    - protocol: 'TCP'
      port: 443
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-prod-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: testapp-prod
      tier: backend
  template:
    metadata:
      labels:
        app: testapp-prod
        tier: backend
    spec:
      containers:
        - name: testapp-prod
          image: kns1997/testapp-prod:1.0.0
          command: ["npm", "run", "start:prod"]
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 60
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: regcred
