services:
  backend-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    image: testapp-dev:latest
    container_name: testapp-dev
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - '443'
    ports:
      - '443:3000'
    command: npm run watch:dev
